version: '2'
services:
    web:
        restart: always
        container_name: web
        build: .
        expose:
            - "8000"
        env_file: .env
        volumes:
            - ./web:/web
        links:
            - db:db
        depends_on:
            - db
        command: ./entrypoint.sh